source 'https://rubygems.org'

gem 'activerecord', '~> 5.2', '>= 5.2.2', require: 'active_record'

gem 'pg', '~> 1.1', '>= 1.1.3'
gem 'mysql2', '~> 0.5.2'
gem 'sqlite3', '~> 1.3', '>= 1.3.13'

gem 'pg_party', '~> 0.7.3'
