#
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('Gemfile', __dir__)
require 'bundler/setup'

#
Bundler.require(:default)

#
require 'ostruct'
require 'pathname'
require 'yaml'

Rails = OpenStruct.new
root = Pathname.new(File.expand_path('..', __FILE__))
Rails.root = root
env = ActiveSupport::StringInquirer.new('production')
Rails.env = env

class SeedLoader
  def load_seed
  end
end

include ActiveRecord::Tasks
DatabaseTasks.env = env
DatabaseTasks.database_configuration = YAML.load_file(root.join('config/database.yml').to_s)
DatabaseTasks.db_dir = root.join('db').to_s
DatabaseTasks.migrations_paths = [root.join('db/migrate').to_s]
DatabaseTasks.seed_loader = SeedLoader.new
DatabaseTasks.root = root

#
namespace :db do
  task :load_config do
    ActiveRecord::Base.configurations       = DatabaseTasks.database_configuration
    ActiveRecord::Migrator.migrations_paths = DatabaseTasks.migrations_paths
  end

  desc "Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)."
  task migrate: [:load_config] do
    DatabaseTasks.migrate
  end

  desc "Rolls the schema back to the previous version (specify steps w/ STEP=n)."
  task rollback: [:load_config] do
    step = ENV["STEP"] ? ENV["STEP"].to_i : 1
    ActiveRecord::Base.connection.migration_context.rollback(step)
  end
end
